---
title: "Proximal gradient descent"
author: "Yinan Zhu"
date: "October 17, 2017"
output: html_document
---

```{r}
library(glmnet)
source('~/GitHub/SDS385-course-work/Excercise 6 Proximal gradient descent/proximal gradient descent/functions.R')
X <- read.csv("~/GitHub/SDS385-course-work/Excercise 6 Proximal gradient descent/proximal gradient descent/diabetesX.csv", header=TRUE)
Y = read.csv("~/GitHub/SDS385-course-work/Excercise 6 Proximal gradient descent/proximal gradient descent/diabetesY.csv", header=FALSE)
X = as.matrix(X)
X = scale(X)
X=cbind(1,X)
Y = Y$V1
Y = as.vector(scale(Y))
n=length(Y)
p=ncol(X)
```
```{r}
lam=seq(from=0.001,to=0.6,by=0.005)
```
```{r}
beta0=rep(0,p)
lambda=0.001
gamma=0.1
ite=400
```

```{r}
result=prox_gd(X,Y,beta0,lambda,gamma,ite)
plot(result$targetfunction,type='l',xlab='iteration',ylab='target function')
convergence=result$targetfunction
```


```{r}
mse=rep(0,0)
betahistory=matrix(nrow=0,ncol=p)
for(lambda in lam){
  result=prox_gd(X,Y,beta0,lambda,gamma,ite)
  betahistory=rbind(betahistory,result$beta)
  mse=c(mse,target_function(X,Y,result$beta,0))
}
plot(mse~lam,type='l',xlab='lambda')
```
```{r}
plot(0,type='l',xlim=c(-7,0),ylim=c(-0.4,0.4),ylab='coefficient',xlab='log(lambda)')
for(i in 2:ncol(betahistory)){
  lines(betahistory[,i]~log(lam))
}
```

```{r}
m = glmnet(X,Y,lambda=lam)
yhat=predict(m,newx=X)
plot(colMeans((Y-yhat)^2)~m$lambda,type='l',ylab='mse',xlab='lambda')
```
```{r}
plot.glmnet(m,xvar='lambda')
```

```{r}
lambda=0.001
result=acc_prox_gd(X,Y,beta0,lambda,gamma,ite)
plot(result$targetfunction,type='l',xlab='iteration',ylab='target function')
lines(convergence,col='red')
acc_convergence=result$targetfunction
```

```{r}
s=2
x=rep(0,0)
for(i in 1:1000){
  x=c(x,2*(s-1)/(1+sqrt(1+4*s^2)))
  s=(1+sqrt(1+4*s^2))/2
}
plot(x,type='l')
```
```{r}
result=lazy_acc_prox_gd(X,Y,beta0,lambda,gamma,ite,0.8)
plot(result$targetfunction,type='l',xlab='iteration',ylab='target function')
lines(convergence,col='red')
lines(acc_convergence,col='blue')
legend('topright',col=c('black','red','blue'),lty=1,legend=c('proximal','accelarated proximal','accelarated proximal with fixed momentum'))
```
