---
title: "Stochastic gradient descent with adagrad"
author: "Yinan Zhu"
date: "September 27, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(readr)
data <- read_csv("~/GitHub/SDS385-course-work/Excercise 2 Stochastic gradient descent/stochastic gradient descent/wdbc.csv",col_names = FALSE)
source('~/GitHub/SDS385-course-work/Excercise 4 Dealing with large data set/adagrad/gradient descent functions.R')
```
```{r}
X=as.matrix(data[3:12])
X=scale(X)
X=cbind(X,1)
y=as.vector(matrix(nrow=nrow(data),ncol=1))
for(i in 1:nrow(data)){
  if(data[i,2]=="M")y[i]=1
  else y[i]=0
}
beta0=as.vector(matrix(0,nrow=11))

trainX=X[1:400,]
trainy=y[1:400]
testX=X[401:569,]
testy=y[401:569]
```


```{r}
ite=1000
```

```{r}
eps=0.005
result=sgd(trainX,trainy,beta0,eps,ite)
test_negloglikelihood = rep(0,ite)
train_negloglikelihood = rep(0,ite)
for(i in 1 : ite){
og = omega(testX,result[,i])
test_negloglikelihood[i] = nllh(og,testy)/length(testy)
og = omega(trainX, result[,i])
train_negloglikelihood[i] = nllh(og,trainy)/length(trainy)
}
plot(train_negloglikelihood,type='l',ylab='negative loglikelihood',xlab='iteration',sub='gradient search step size 0.005')
lines(test_negloglikelihood,col='red')
legend('topright',col=c('black','red'),legend=c('training data (moving average)','test data'),lty=1)
smalleps_nllh=train_negloglikelihood
```

```{r}
eps=0.02
result=sgd(trainX,trainy,beta0,eps,ite)
test_negloglikelihood = rep(0,ite)
train_negloglikelihood = rep(0,ite)
for(i in 1 : ite){
og = omega(testX,result[,i])
test_negloglikelihood[i] = nllh(og,testy)/length(testy)
og = omega(trainX, result[,i])
train_negloglikelihood[i] = nllh(og,trainy)/length(trainy)
}
plot(train_negloglikelihood,type='l',ylab='negative loglikelihood',xlab='',sub='gradient search step size 0.02')
lines(test_negloglikelihood,col='red')
legend('topright',col=c('black','red'),legend=c('training data (moving average)','test data'),lty=1)
bigeps_nllh=train_negloglikelihood
```

Now with ada grad
```{r}
eps=1
result=sgd_adagrad(trainX,trainy,beta0,eps,ite)
test_negloglikelihood = rep(0,ite)
train_negloglikelihood = rep(0,ite)
for(i in 1 : ite){
og = omega(testX,result[,i])
test_negloglikelihood[i] = nllh(og,testy)/length(testy)
og = omega(trainX, result[,i])
train_negloglikelihood[i] = nllh(og,trainy)/length(trainy)
}
plot(train_negloglikelihood,type='l',ylab='negative loglikelihood',xlab='',sub='gradient search with ada_grad')
lines(test_negloglikelihood,col='red')
legend('topright',col=c('black','red'),legend=c('training data (moving average)','test data'),lty=1)
adagrad_nllh=train_negloglikelihood
```

summarize
```{r}
plot(adagrad_nllh,type='l',ylab='negative loglikelihood',xlab='iteration')
lines(bigeps_nllh,col='blue')
lines(smalleps_nllh,col='purple')
legend('topright',col=c('black','blue','purple'),legend=c('step size 0.005','step size 0.02','ada grad'),lty=1)
```


